### ISSUE TITLE
can not send friend request 

### ISSUE THREAD

**Issue by xiamao** [lijiarui/wechaty-puppet-padchat#166] opened 2018-08-30 07:36 UTC
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
Beijing
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
AliYun

### Full Output Logs

```shell
# PASTE FULL LOG OUTPUT AT HERE:
Send a Friend Request to a contact with message hello
14:34:07 SILL Accessory #2<Room> constructor()
14:34:07 SILL Room constructor(10791082533@chatroom)
14:34:07 VERB Room memberList()
14:34:07 VERB PuppetPadchat roomMemberList(10791082533@chatroom)
14:34:07 VERB PuppetPadchatManager getRoomMemberIdList(10791082533)
14:34:07 VERB PuppetPadchatManager getRoomMemberIdList(10791082533) length=2
14:34:07 SILL PuppetPadchat roomMemberList()=2
14:34:07 VERB Contact load(wxid_u80vgxwdopa312) init pool
14:34:07 SILL Accessory #3<Contact> constructor()
14:34:07 SILL Contact constructor(wxid_u80vgxwdopa312)
14:34:07 SILL Accessory #4<Contact> constructor()
14:34:07 SILL Contact constructor(wxid_7498284983512)
14:34:07 VERB Friendship static add(wxid_u80vgxwdopa312, hello)
14:34:07 VERB PuppetPadchat friendshipAdd(wxid_u80vgxwdopa312, hello)
14:34:07 SILL PadchatRpc rpcCall(WXSearchContact, ["wxid_u80vgxwdopa312"])
14:34:07 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXSearchContact","data":"%7B%22big_head%22%3A%22%22%2C%22city%22%3A%22%22%2C%22country%2
14:34:07 SILL PadchatRpc initHeartbeat() throttleQueue.subscribe(ws.on(message))
14:34:07 SILL PuppetPadchat startWatchdog() padchatManager.on(heartbeat)
14:34:07 SILL Wechaty memoryCheck() free: 772 MB, require: 4 MB
14:34:07 SILL PadchatRpc WXSearchContact result: {"big_head":"","city":"","country":"","message":"\n�\u0002<e>\n<ShowType>1</ShowType>\n<Content><![CDATA[找不到相关帐号或内容]]></Content>\n<Url><![CDATA[]]></Url>\n<DispSec>30</DispSec>\n<Title><![CDATA[]]></Title>\n<Action>2</Action>\n<DelayConnSec>0</DelayConnSec>\n<Countdown>0</Countdown>\n<Ok><![CDATA[]]></Ok>\n<Cancel><![CDATA[]]></Cancel>\n</e>\n","nick_name":"","provincia":"","py_initial":"","quan_pin":"","sex":0,"signature":"","small_head":"","status":-24,"stranger":"","user_name":""}
14:34:07 VERB PadchatRpc WXSearchContact wxid: wxid_u80vgxwdopa312 cannot be searched
14:34:07 ERR Config ###########################
14:34:07 ERR Config unhandledRejection: Error: stranger neither v1 nor v2! [object Promise]
14:34:07 ERR Config ###########################
14:34:07 ERR Config process.on(unhandledRejection) promise.catch(stranger neither v1 nor v2!)
Config Error: stranger neither v1 nor v2!
    at PuppetPadchat.<anonymous> (/bot/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:1473:13)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

### mycode
```
const sRoom = await bot.Room.load('10791082533@chatroom');
const memberList = await sRoom.memberList();
for (let i = 0; i < memberList.length; i++) {
      await bot.Friendship.add(memberList[i], msgHello)
}
```

**Comment by windmemory** [comment] 2018-09-02 09:52
After some investigation, I found that this is the limitation on protocol level. `contactId` start with `wxid` can not be searched, so they can not be added. 

Added an error message for this kind of contact with a0f27621f547b3620cb47cc0c20d3ddb3748e1a8

Close this issue for now since this is not a bug.

**Closed by windmemory** 2018-09-02 09:52 UTC
Labels: bug
